// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '858999507653',
    projectId: 'weather-app-d1c43',
    authDomain: 'weather-app-d1c43.firebaseapp.com',
    storageBucket: 'weather-app-d1c43.firebasestorage.app',
    measurementId: 'G-2E5B22DELX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-JETT6POmOZeFFJRsUExAYVyQ_14QYME',
    appId: '1:858999507653:android:7d095adb48d2f2a5f1beac',
    messagingSenderId: '858999507653',
    projectId: 'weather-app-d1c43',
    storageBucket: 'weather-app-d1c43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonX9RiRnOF1vbgWEA2eCG3x7LdgaUNrE',
    appId: '1:858999507653:ios:a9a7f3791e29666ff1beac',
    messagingSenderId: '858999507653',
    projectId: 'weather-app-d1c43',
    storageBucket: 'weather-app-d1c43.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonX9RiRnOF1vbgWEA2eCG3x7LdgaUNrE',
    appId: '1:858999507653:ios:a9a7f3791e29666ff1beac',
    messagingSenderId: '858999507653',
    projectId: 'weather-app-d1c43',
    storageBucket: 'weather-app-d1c43.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRo4EuWG9-mVd3XVoMTXbXo8dHg9lrIkE',
    appId: '1:858999507653:web:d0bae8bac7051748f1beac',
    messagingSenderId: '858999507653',
    projectId: 'weather-app-d1c43',
    authDomain: 'weather-app-d1c43.firebaseapp.com',
    storageBucket: 'weather-app-d1c43.firebasestorage.app',
    measurementId: 'G-WM0DGVNYTH',
  );
}
